### ISSUE TITLE
支持小米手环8Pro

### ISSUE THREAD

**Issue by xinghengCN** [Searchstars/HyperBilibili#1]
希望添加HyperBili安卓中间传输端，使用设备通信功能传输信息到手环））

**Comment by Searchstars** [comment]
按照小米惯例，最多再等3 4个月，手环9就出了，然后再过一两个月，手环9p也得出来了，9是不是vela不好说，但我个人认为9p绝对会上vela，并且以hyperos的名字面向公众，届时也应该支持fetch api，我还是更倾向于等下一代。
但是你的建议我也会考虑，但目前对于这么一个还处于功能完善阶段的项目而言这不是首要的目标

**Comment by OnDriveLine** [comment]
9Pro看上去出不了那么快啊哥们，8Pro是不是能支持起来了
